### ISSUE TITLE
ValueError when running the code

### ISSUE THREAD

**Issue by Kaustubhk12** [nlml/bpm#2]
\bpm-master>python mp3s_to_fft_features.py

each clip will be 1.8634013605442177 seconds long
resolution is 85.8644859813084 frames per second
Traceback (most recent call last):
  File "mp3s_to_fft_features.py", line 39, in <module>
    X, y, bpms, fnames = ns.get_spectogram_training_set(n_batch=NUM_TRAIN)
  File "\bpm-master\NeuralSounds.py", line 165, in get_spectogram_training_set
    fname = np.random.choice(self.track_fnames, 1)[0]
  File "mtrand.pyx", line 1397, in mtrand.RandomState.choice (numpy\random\mtrand\mtrand.c:16526)
ValueError: a must be non-empty

**Comment by nlml** [comment]
Hmmm.. seems like the fnames list might be empty? Perhaps look into how that is created and see why it might be empty...
